import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppIcon } from '@/components/app-icon';
import { Avatar } from '@/components/avatar';
import { Screen } from '@/components/screen';
import { professionals } from '@/mocks/data';
import { professionalArticles } from '@/mocks/discovery';
import { colors, layout, radius, shadow, spacing, typography } from '@/theme/tokens';

export default function ArticleDetail() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const article = professionalArticles.find(item => item.id === id) ?? professionalArticles[0];
  const author = professionals.find(item => item.id === article.authorId)!;
  return <Screen scroll style={styles.screen}><View style={styles.content}>
    <View style={styles.top}><Pressable onPress={() => router.back()} style={styles.iconButton}><AppIcon name="arrow_back" color={colors.ocean700} /></Pressable><View style={styles.topActions}><Pressable style={styles.iconButton}><AppIcon name="bookmark" color={colors.ocean700} /></Pressable><Pressable style={styles.iconButton}><AppIcon name="ios_share" color={colors.ocean700} /></Pressable></View></View>
    <View style={styles.hero}>{article.pinned && <View style={styles.pinned}><AppIcon name="push_pin" filled size={15} color={colors.white} /><Text style={styles.pinnedText}>PINNED BY {author.displayName.toUpperCase()}</Text></View>}<Text style={styles.topic}>{article.topic} · {article.evidenceLevel}</Text><Text style={styles.title}>{article.title}</Text><Text style={styles.summary}>{article.summary}</Text><View style={styles.author}><Avatar name={author.displayName} size={48} verified /><View style={{ flex: 1 }}><Text style={styles.authorName}>{author.displayName}</Text><Text style={styles.authorMeta}>{author.title} · {article.publishedAt} · {article.readTime}</Text></View></View></View>
    <View style={styles.review}><AppIcon name="verified_user" color={colors.ocean600} /><View style={{ flex: 1 }}><Text style={styles.reviewTitle}>Professional educational content</Text><Text style={styles.reviewText}>The author’s identity and credentials are verified. This article was reviewed for safety and clear professional boundaries.</Text></View></View>
    {article.sections.map((section, index) => <View key={section.heading} style={styles.section}><View style={styles.sectionNumber}><Text style={styles.sectionNumberText}>{index + 1}</Text></View><View style={{ flex: 1 }}><Text style={styles.sectionTitle}>{section.heading}</Text><Text style={styles.body}>{section.body}</Text></View></View>)}
    <View style={styles.takeaways}><View style={styles.takeawayHead}><AppIcon name="lightbulb" filled color={colors.sun} /><Text style={styles.takeawayTitle}>Key takeaways</Text></View>{article.takeaways.map(item => <View key={item} style={styles.takeaway}><AppIcon name="check_circle" filled size={18} color={colors.ocean500} /><Text style={styles.takeawayText}>{item}</Text></View>)}</View>
    <View style={styles.helpful}><View><Text style={styles.helpfulTitle}>Was this article helpful?</Text><Text style={styles.helpfulText}>{article.helpfulCount} community members said yes</Text></View><Pressable style={styles.helpfulButton}><AppIcon name="favorite" color={colors.coral} /><Text style={styles.helpfulButtonText}>Helpful</Text></Pressable></View>
    <View style={styles.references}><Text style={styles.referencesTitle}>Review & references</Text>{article.references.map(item => <Text key={item} style={styles.reference}>• {item}</Text>)}</View>
    <Text style={styles.disclaimer}>This article provides general educational information. It is not a diagnosis, treatment plan, or substitute for professional medical care.</Text>
  </View></Screen>;
}

const styles = StyleSheet.create({
  screen: { padding: 0 }, content: { width: '100%', maxWidth: layout.maxContent, alignSelf: 'center', padding: spacing.md, gap: spacing.lg }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, topActions: { flexDirection: 'row', gap: spacing.sm }, iconButton: { width: 40, height: 40, borderRadius: radius.pill, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  hero: { backgroundColor: colors.white, borderRadius: radius.xl, borderWidth: 1, borderColor: colors.border, padding: spacing.xl, gap: spacing.md, ...shadow.soft }, pinned: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: colors.ocean700, borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 5 }, pinnedText: { color: colors.white, fontSize: 8, fontWeight: '900', letterSpacing: .8 }, topic: { color: colors.ocean600, fontSize: 10, fontWeight: '900', letterSpacing: .5 }, title: { color: colors.ink, fontSize: 32, lineHeight: 41, fontWeight: '900' }, summary: { color: colors.inkSoft, fontSize: 15, lineHeight: 24 }, author: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.md }, authorName: { color: colors.ink, fontSize: 12, fontWeight: '900' }, authorMeta: { color: colors.muted, fontSize: 9, marginTop: 3 },
  review: { flexDirection: 'row', gap: spacing.sm, backgroundColor: colors.ocean50, borderRadius: radius.lg, padding: spacing.md }, reviewTitle: { color: colors.ink, fontSize: 11, fontWeight: '900' }, reviewText: { color: colors.muted, fontSize: 10, lineHeight: 16, marginTop: 3 }, section: { flexDirection: 'row', gap: spacing.md }, sectionNumber: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.ocean100, alignItems: 'center', justifyContent: 'center' }, sectionNumberText: { color: colors.ocean700, fontWeight: '900' }, sectionTitle: { color: colors.ink, fontSize: typography.h2, lineHeight: 29, fontWeight: '900' }, body: { color: colors.inkSoft, fontSize: 15, lineHeight: 26, marginTop: spacing.sm },
  takeaways: { backgroundColor: colors.sunSoft, borderRadius: radius.xl, padding: spacing.lg, gap: spacing.sm }, takeawayHead: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, takeawayTitle: { color: colors.ink, fontSize: typography.h3, fontWeight: '900' }, takeaway: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, takeawayText: { flex: 1, color: colors.inkSoft, fontSize: 12, lineHeight: 18 }, helpful: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.md }, helpfulTitle: { color: colors.ink, fontWeight: '900' }, helpfulText: { color: colors.muted, fontSize: 10, marginTop: 3 }, helpfulButton: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: colors.coralSoft, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, helpfulButtonText: { color: colors.coral, fontSize: 11, fontWeight: '900' }, references: { gap: spacing.sm }, referencesTitle: { color: colors.ink, fontSize: 13, fontWeight: '900' }, reference: { color: colors.muted, fontSize: 10, lineHeight: 16 }, disclaimer: { color: colors.muted, fontSize: 9, lineHeight: 15, textAlign: 'center', paddingHorizontal: spacing.lg },
});
