import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppIcon } from '@/components/app-icon';
import { Avatar } from '@/components/avatar';
import { PostCard } from '@/features/content/post-card';
import { useLanguage } from '@/localization/language-provider';
import { categories, mockPosts, Professional, professionals } from '@/mocks/data';
import { professionalArticles } from '@/mocks/discovery';
import { colors, layout, radius, shadow, spacing, typography } from '@/theme/tokens';

const featuredCategories = [
  ...categories.filter(category => category.group === 'EMOTION').slice(0, 2),
  ...categories.filter(category => category.group === 'CONDITION').slice(0, 3),
  ...categories.filter(category => category.group === 'LIFE_EXPERIENCE').slice(0, 3),
];

const groupNames = { EMOTION: 'Emotion', CONDITION: 'Condition', LIFE_EXPERIENCE: 'Life experience' } as const;
const checkInOptions = [
  { id: 'rough', icon: 'sentiment_very_dissatisfied', label: 'Rough', color: colors.coral },
  { id: 'low', icon: 'sentiment_dissatisfied', label: 'Low', color: colors.lavender },
  { id: 'okay', icon: 'sentiment_neutral', label: 'Okay', color: colors.sky },
  { id: 'good', icon: 'sentiment_satisfied', label: 'Good', color: colors.ocean500 },
  { id: 'calm', icon: 'self_improvement', label: 'Calm', color: colors.ocean700 },
];

export default function FeedScreen() {
  const { t } = useLanguage();
  const [tab, setTab] = useState<'forYou' | 'following' | 'professionalAnswers'>('forYou');
  const [categoryId, setCategoryId] = useState('all');
  const [checkIn, setCheckIn] = useState('');
  const shown = useMemo(() => mockPosts.filter(post => (tab !== 'professionalAnswers' || post.professionalReply) && (categoryId === 'all' || post.categoryId === categoryId)), [tab, categoryId]);
  const pinnedArticle = professionalArticles.find(article => article.pinned)!;
  const articleAuthor = professionals.find(professional => professional.id === pinnedArticle.authorId)!;

  const header = <View style={styles.headerContent}>
    <View style={styles.top}>
      <View><Text style={styles.brand}>GreenOcean</Text><Text style={styles.hello}>{t('moodQuestion')}</Text></View>
      <View style={styles.topActions}><Pressable accessibilityRole="button" onPress={() => router.push('/notifications')} style={styles.round} accessibilityLabel="Activity"><AppIcon name="notifications" color={colors.ocean700} /><View style={styles.alertDot} /></Pressable><Pressable accessibilityRole="button" onPress={() => router.push('/support')} style={styles.round} accessibilityLabel="Support now"><AppIcon name="health_and_safety" color={colors.ocean700} /></Pressable><Avatar name="Taylor" size={42} /></View>
    </View>

    <Pressable accessibilityRole="button" accessibilityLabel="Talk privately with a trained listener" onPress={() => router.push('/support')} style={styles.supportStrip}><View style={styles.supportIcon}><AppIcon name="hearing" color={colors.ocean800} /></View><View style={{ flex: 1 }}><Text style={styles.supportLabel}>NEED SOMEONE RIGHT NOW?</Text><Text style={styles.supportTitle}>Talk privately with a trained listener</Text><Text style={styles.supportMeta}>18 listeners online · Usually under 2 minutes</Text></View><View style={styles.supportAction}><Text style={styles.supportActionText}>Talk now</Text><AppIcon name="arrow_forward" size={17} color={colors.white} /></View></Pressable>

    <View style={styles.checkIn}><View style={styles.checkInHead}><View><Text style={styles.checkInTitle}>How are you, really?</Text><Text style={styles.checkInText}>{checkIn ? 'Thanks for checking in. Your feed will adapt gently.' : 'A private check-in for better recommendations.'}</Text></View>{!!checkIn && <AppIcon name="check_circle" filled color={colors.ocean500} />}</View><View style={styles.checkInOptions}>{checkInOptions.map(option => <Pressable key={option.id} accessibilityRole="radio" accessibilityLabel={`Feeling ${option.label}`} accessibilityState={{ checked: checkIn === option.id }} onPress={() => setCheckIn(option.id)} style={[styles.checkInOption, checkIn === option.id && { backgroundColor: option.color, borderColor: option.color }]}><AppIcon name={option.icon} size={21} color={checkIn === option.id ? colors.white : option.color} /><Text style={[styles.checkInLabel, checkIn === option.id && { color: colors.white }]}>{option.label}</Text></Pressable>)}</View></View>

    <Pressable accessibilityRole="button" accessibilityLabel="Create a new post" onPress={() => router.push('/create')} style={styles.composer}><Avatar name="Taylor" size={38} /><Text style={styles.composerText}>{t('sharePrompt')}</Text><View style={styles.composeIcon}><AppIcon name="edit" size={18} color={colors.white} /></View></Pressable>

    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{(['forYou', 'following', 'professionalAnswers'] as const).map(item => <Pressable accessibilityRole="tab" accessibilityState={{ selected: tab === item }} key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.activeTab]}><Text style={[styles.tabText, tab === item && styles.activeTabText]}>{t(item)}</Text></Pressable>)}</ScrollView>

    <View style={styles.sectionHead}><View><Text style={styles.eyebrow}>FIND YOUR SPACE</Text><Text style={styles.sectionTitle}>Browse stories by topic</Text></View><Pressable accessibilityRole="button" onPress={() => router.push('/search')}><Text style={styles.seeAll}>{t('seeAll')}</Text></Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.categoryRail}>
      <Pressable accessibilityRole="radio" accessibilityState={{ checked: categoryId === 'all' }} onPress={() => setCategoryId('all')} style={[styles.categoryCard, categoryId === 'all' && styles.categoryCardActive]}><View style={[styles.categoryIcon, { backgroundColor: categoryId === 'all' ? colors.ocean600 : colors.ocean100 }]}><AppIcon name="grid_view" color={categoryId === 'all' ? colors.white : colors.ocean700} /></View><Text style={[styles.categoryName, categoryId === 'all' && styles.categoryNameActive]}>{t('allCategories')}</Text><Text style={styles.categoryCount}>All emotions, conditions & experiences</Text></Pressable>
      {featuredCategories.map(category => <Pressable accessibilityRole="radio" accessibilityState={{ checked: categoryId === category.id }} key={category.id} onPress={() => setCategoryId(category.id)} style={[styles.categoryCard, categoryId === category.id && styles.categoryCardActive]}><View style={[styles.categoryIcon, { backgroundColor: category.softColor }]}><AppIcon name={category.icon} color={category.color} /></View><Text style={styles.categoryGroup}>{groupNames[category.group]}</Text><Text style={[styles.categoryName, categoryId === category.id && styles.categoryNameActive]}>{category.name}</Text><Text style={styles.categoryCount}>{category.postCount.toLocaleString()} stories</Text></Pressable>)}
    </ScrollView>

    <View style={styles.feedHeading}><Text style={styles.feedTitle}>{categoryId === 'all' ? (tab === 'forYou' ? t('forYou') : t(tab)) : categories.find(category => category.id === categoryId)?.name}</Text>{categoryId !== 'all' && <Pressable accessibilityRole="button" onPress={() => setCategoryId('all')}><Text style={styles.clear}>Clear filter</Text></Pressable>}</View>
  </View>;

  const footer = <View style={styles.footerContent}>
    <View style={styles.sectionHead}><View><Text style={styles.eyebrow}>CONTINUE EXPLORING</Text><Text style={styles.sectionTitle}>Knowledge, culture & professional support</Text></View></View>
    <View style={styles.discoveryGrid}>
      <Pressable accessibilityRole="button" onPress={() => router.push('/articles')} style={[styles.discoveryCard, styles.knowledgeCard]}><View style={styles.discoveryIcon}><AppIcon name="science" color={colors.ocean700} /></View><View style={{ flex: 1 }}><Text style={styles.discoveryLabel}>KNOWLEDGE HUB</Text><Text style={styles.discoveryTitle}>Articles by verified professionals</Text></View><AppIcon name="arrow_forward" color={colors.ocean700} /></Pressable>
      <Pressable accessibilityRole="button" onPress={() => router.push('/media')} style={[styles.discoveryCard, styles.watchCard]}><View style={[styles.discoveryIcon, { backgroundColor: colors.lavenderSoft }]}><AppIcon name="movie" color={colors.lavender} /></View><View style={{ flex: 1 }}><Text style={[styles.discoveryLabel, { color: colors.lavender }]}>WATCH & REFLECT</Text><Text style={styles.discoveryTitle}>Psychology movies & series</Text></View><AppIcon name="arrow_forward" color={colors.lavender} /></Pressable>
    </View>
    <View style={styles.sectionHead}><View><Text style={styles.eyebrow}>FEATURED PLACEMENT</Text><Text style={styles.sectionTitle}>Professionals for today</Text></View><Pressable accessibilityRole="button" onPress={() => router.push('/professionals')}><Text style={styles.seeAll}>Compare all</Text></Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.experts}>{professionals.filter(professional => professional.promoted).map(professional => <DoctorBanner key={professional.id} professional={professional} />)}</ScrollView>
    <View style={styles.sectionHead}><View><Text style={styles.eyebrow}>PINNED SCIENTIFIC ARTICLE</Text><Text style={styles.sectionTitle}>A professional perspective</Text></View><Pressable accessibilityRole="button" onPress={() => router.push('/articles')}><Text style={styles.seeAll}>Knowledge Hub</Text></Pressable></View>
    <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/article/[id]', params: { id: pinnedArticle.id } })} style={styles.articleFeature}><View style={styles.pin}><AppIcon name="push_pin" filled size={16} color={colors.white} /><Text style={styles.pinText}>PINNED BY {articleAuthor.displayName.toUpperCase()}</Text></View><View style={styles.articleBody}><Text style={styles.articleTopic}>{pinnedArticle.topic} · {pinnedArticle.readTime}</Text><Text style={styles.articleTitle}>{pinnedArticle.title}</Text><Text style={styles.articleSummary}>{pinnedArticle.summary}</Text><View style={styles.articleFooter}><Avatar name={articleAuthor.displayName} size={34} verified /><Text style={styles.articleAuthor}>{articleAuthor.displayName}<Text style={styles.articleRole}> · {articleAuthor.title}</Text></Text><AppIcon name="arrow_forward" color={colors.ocean700} /></View></View></Pressable>
  </View>;

  return <SafeAreaView style={styles.safe}><FlatList data={shown} keyExtractor={item => item.id} renderItem={({ item }) => <PostCard post={item} />} ListHeaderComponent={header} ListFooterComponent={footer} contentContainerStyle={styles.list} ItemSeparatorComponent={() => <View style={{ height: spacing.md }} />} ListEmptyComponent={<View style={styles.empty}><AppIcon name="forum" size={36} color={colors.ocean500} /><Text style={styles.emptyTitle}>No stories in this category yet</Text><Text style={styles.emptyText}>Be the first person to share an experience here.</Text></View>} showsVerticalScrollIndicator={false} /></SafeAreaView>;
}

function DoctorBanner({ professional }: { professional: Professional }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={`View profile for ${professional.displayName}`} onPress={() => router.push({ pathname: '/profile', params: { professional: professional.id } })} style={styles.doctorBanner}>
    <View style={styles.bannerGlow} />
    <View style={styles.sponsored}><AppIcon name="campaign" size={14} color={colors.ocean300} /><Text style={styles.sponsoredText}>FEATURED · SPONSORED</Text></View>
    <View style={styles.bannerMain}><Avatar name={professional.displayName} size={66} verified /><View style={styles.bannerCopy}><Text style={styles.expertName}>{professional.displayName}</Text><Text style={styles.expertTitle}>{professional.title} · {professional.city}</Text><View style={styles.specialties}>{professional.specialties.slice(0, 2).map(specialty => <Text key={specialty} style={styles.specialty}>{specialty}</Text>)}</View></View><View style={styles.scoreBadge}><Text style={styles.scoreValue}>{professional.greenOceanScore}</Text><Text style={styles.scoreLabel}>GO SCORE</Text></View></View>
    <View style={styles.bannerBottom}><View style={styles.rating}><AppIcon name="star" filled size={17} color={colors.sun} /><Text style={styles.ratingText}>{professional.rating} · {professional.reviewCount} reviews</Text></View><Text style={styles.bannerReason}>{professional.promotedReason}</Text><View style={styles.viewProfile}><Text style={styles.viewProfileText}>View profile</Text><AppIcon name="arrow_forward" size={17} color={colors.white} /></View></View>
  </Pressable>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.foam }, list: { width: '100%', maxWidth: layout.maxContent, alignSelf: 'center', paddingHorizontal: spacing.md, paddingBottom: spacing.xxxl }, headerContent: { gap: spacing.md }, footerContent: { gap: spacing.md, paddingTop: spacing.xl },
  top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: spacing.sm }, brand: { fontSize: 22, fontWeight: '900', color: colors.ocean800 }, hello: { fontSize: 12, color: colors.muted, marginTop: 2 }, topActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, round: { width: 40, height: 40, borderRadius: radius.pill, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, alertDot: { position: 'absolute', right: 8, top: 7, width: 7, height: 7, borderRadius: 4, backgroundColor: colors.coral, borderWidth: 1, borderColor: colors.white },
  composer: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.white, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, padding: spacing.sm, ...shadow.soft }, composerText: { flex: 1, color: colors.muted, fontSize: 14, textAlign: 'left' }, composeIcon: { width: 34, height: 34, borderRadius: radius.pill, backgroundColor: colors.ocean600, alignItems: 'center', justifyContent: 'center' },
  supportStrip: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.ocean950, borderRadius: radius.lg, padding: spacing.md, ...shadow.soft }, supportIcon: { width: 42, height: 42, borderRadius: radius.sm, backgroundColor: colors.ocean200, alignItems: 'center', justifyContent: 'center' }, supportLabel: { color: colors.ocean300, fontSize: 7, fontWeight: '900', letterSpacing: .8 }, supportTitle: { color: colors.white, fontSize: 12, fontWeight: '900', marginTop: 2 }, supportMeta: { color: colors.ocean200, fontSize: 8, marginTop: 3 }, supportAction: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: colors.ocean500, borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 8 }, supportActionText: { color: colors.white, fontSize: 9, fontWeight: '900' },
  checkIn: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.md, gap: spacing.sm }, checkInHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, checkInTitle: { color: colors.ink, fontSize: 13, fontWeight: '900' }, checkInText: { color: colors.muted, fontSize: 9, marginTop: 3 }, checkInOptions: { flexDirection: 'row', gap: 6 }, checkInOption: { flex: 1, minHeight: 52, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.foam, alignItems: 'center', justifyContent: 'center', gap: 2 }, checkInLabel: { color: colors.muted, fontSize: 7, fontWeight: '800' },
  discoveryGrid: { gap: spacing.sm }, discoveryCard: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderRadius: radius.lg, padding: spacing.md, borderWidth: 1 }, knowledgeCard: { backgroundColor: colors.ocean50, borderColor: colors.ocean200 }, watchCard: { backgroundColor: '#F8F6FC', borderColor: '#DED7F1' }, discoveryIcon: { width: 42, height: 42, borderRadius: radius.sm, backgroundColor: colors.ocean100, alignItems: 'center', justifyContent: 'center' }, discoveryLabel: { fontSize: 9, letterSpacing: 1, color: colors.ocean600, fontWeight: '900' }, discoveryTitle: { color: colors.ink, fontSize: 13, fontWeight: '900', marginTop: 3 },
  tabs: { gap: spacing.sm, paddingVertical: spacing.xs }, tab: { paddingHorizontal: spacing.md, paddingVertical: 10, borderRadius: radius.pill, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border }, activeTab: { backgroundColor: colors.ocean900, borderColor: colors.ocean900 }, tabText: { color: colors.muted, fontSize: 13, fontWeight: '700' }, activeTabText: { color: colors.white },
  sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: spacing.sm }, eyebrow: { fontSize: 9, color: colors.ocean600, fontWeight: '900', letterSpacing: 1.1, marginBottom: 3 }, sectionTitle: { fontSize: typography.h3, fontWeight: '900', color: colors.ink }, seeAll: { fontSize: 11, color: colors.ocean600, fontWeight: '800' },
  categoryRail: { gap: spacing.sm, paddingBottom: spacing.xs }, categoryCard: { width: 132, minHeight: 106, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.sm, gap: 4 }, categoryCardActive: { borderColor: colors.ocean500, backgroundColor: colors.ocean50 }, categoryIcon: { width: 32, height: 32, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center' }, categoryGroup: { fontSize: 7, color: colors.muted, fontWeight: '900', letterSpacing: 0.7, textTransform: 'uppercase' }, categoryName: { fontSize: 11, fontWeight: '900', color: colors.ink }, categoryNameActive: { color: colors.ocean700 }, categoryCount: { fontSize: 8, color: colors.muted, lineHeight: 11 },
  experts: { gap: spacing.sm, paddingBottom: spacing.xs }, doctorBanner: { width: 650, maxWidth: '90%', minHeight: 250, backgroundColor: colors.ocean950, borderRadius: radius.xl, padding: spacing.lg, overflow: 'hidden', gap: spacing.md, ...shadow.floating }, bannerGlow: { position: 'absolute', width: 260, height: 260, borderRadius: 130, backgroundColor: colors.ocean700, right: -70, top: -100, opacity: 0.72 }, sponsored: { flexDirection: 'row', alignItems: 'center', gap: 5 }, sponsoredText: { color: colors.ocean300, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, bannerMain: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, bannerCopy: { flex: 1 }, expertName: { fontSize: 20, fontWeight: '900', color: colors.white }, expertTitle: { fontSize: 11, color: colors.ocean300, marginTop: 4 }, specialties: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: spacing.sm }, specialty: { fontSize: 9, color: colors.white, backgroundColor: '#ffffff18', borderRadius: radius.pill, paddingHorizontal: 8, paddingVertical: 4 }, scoreBadge: { width: 72, height: 72, borderRadius: 36, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, scoreValue: { fontSize: 22, color: colors.ocean800, fontWeight: '900' }, scoreLabel: { fontSize: 7, color: colors.muted, fontWeight: '900' }, bannerBottom: { gap: spacing.sm }, rating: { flexDirection: 'row', alignItems: 'center', gap: 4 }, ratingText: { color: colors.white, fontSize: 11, fontWeight: '800' }, bannerReason: { color: colors.ocean200, fontSize: 10 }, viewProfile: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.ocean500, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 8 }, viewProfileText: { color: colors.white, fontSize: 11, fontWeight: '900' },
  articleFeature: { backgroundColor: colors.white, borderRadius: radius.xl, borderWidth: 1, borderColor: colors.ocean200, overflow: 'hidden', ...shadow.soft }, pin: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.ocean700, paddingHorizontal: spacing.md, paddingVertical: 8 }, pinText: { fontSize: 9, color: colors.white, fontWeight: '900', letterSpacing: 0.7 }, articleBody: { padding: spacing.lg, gap: spacing.sm }, articleTopic: { color: colors.ocean600, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' }, articleTitle: { color: colors.ink, fontSize: 20, lineHeight: 27, fontWeight: '900' }, articleSummary: { color: colors.inkSoft, fontSize: 12, lineHeight: 19 }, articleFooter: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.xs }, articleAuthor: { flex: 1, color: colors.ink, fontSize: 11, fontWeight: '900' }, articleRole: { color: colors.muted, fontWeight: '500' },
  feedHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.sm }, feedTitle: { fontSize: typography.h3, fontWeight: '900', color: colors.ink }, clear: { fontSize: 11, color: colors.ocean600, fontWeight: '800' }, empty: { backgroundColor: colors.white, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, padding: spacing.xl, alignItems: 'center', gap: spacing.sm }, emptyTitle: { color: colors.ink, fontWeight: '900' }, emptyText: { color: colors.muted, fontSize: 13, textAlign: 'center' },
});
