import { router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppIcon } from '@/components/app-icon';
import { Screen } from '@/components/screen';
import { usePlatformData } from '@/features/platform/data-provider';
import { MediaPick } from '@/features/platform/types';
import { apiRequest } from '@/lib/api/client';
import { colors, layout, radius, shadow, spacing, typography } from '@/theme/tokens';

const filters = ['ALL', 'MOVIE', 'SERIES', 'DOCUMENTARY'] as const;

export default function MediaGuide() {
  const { media: mediaPicks, setMedia } = usePlatformData();
  const [filter, setFilter] = useState<(typeof filters)[number]>('ALL');
  const shown = useMemo(() => mediaPicks.filter(item => filter === 'ALL' || item.kind === filter), [filter, mediaPicks]);
  const featured = mediaPicks[0];
  async function toggleSaved(item: MediaPick) {
    const next = !item.saved;
    setMedia(current => current.map(value => value.id === item.id ? { ...value, saved: next } : value));
    try { await apiRequest(`/api/v1/media-recommendations/${item.id}/save`, { method: next ? 'PUT' : 'DELETE' }); }
    catch { setMedia(current => current.map(value => value.id === item.id ? { ...value, saved: !next } : value)); }
  }
  if (!featured) return <Screen style={styles.screen}><View style={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><AppIcon name="arrow_back" color={colors.ocean700} /></Pressable><Text style={styles.count}>No media recommendations are available yet.</Text></View></Screen>;
  return <Screen scroll style={styles.screen}><View style={styles.content}>
    <View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><AppIcon name="arrow_back" color={colors.ocean700} /></Pressable><View style={styles.topIcon}><AppIcon name="bookmark" color={colors.lavender} /></View></View>
    <View><Text style={styles.eyebrow}>WATCH · REFLECT · DISCUSS</Text><Text style={styles.title}>Psychology on screen</Text><Text style={styles.subtitle}>Movies, series, and documentaries selected as conversation starters—not as diagnostic or treatment resources.</Text></View>

    <Pressable style={styles.hero}>
      <LinearGradient colors={['#2D2352', '#6B4F8D', '#F27D69']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.heroGradient}>
        <View style={styles.editorPick}><AppIcon name="stars" filled size={15} color={colors.sun} /><Text style={styles.editorPickText}>EDITOR&apos;S CONVERSATION PICK</Text></View>
        <View style={styles.heroArt}><View style={[styles.emotionOrb, { backgroundColor: '#F4B860', left: 10, top: 24 }]} /><View style={[styles.emotionOrb, { backgroundColor: '#5B9BD5', left: 55, top: 8 }]} /><View style={[styles.emotionOrb, { backgroundColor: '#F27D69', left: 95, top: 39 }]} /><AppIcon name="movie" size={60} color="#ffffff44" /></View>
        <Text style={styles.heroKind}>{featured.kind} · {featured.year} · {featured.duration}</Text><Text style={styles.heroTitle}>{featured.title}</Text><Text style={styles.heroTheme}>{featured.theme}</Text><Text style={styles.heroDescription}>{featured.description}</Text>
        <View style={styles.heroFooter}><View style={styles.recommended}><AppIcon name="verified" filled size={16} color={colors.ocean300} /><Text style={styles.recommendedText}>Recommended by {featured.recommendedBy}</Text></View><View style={styles.exploreButton}><Text style={styles.exploreText}>Explore themes</Text><AppIcon name="arrow_forward" size={18} color={colors.ocean950} /></View></View>
      </LinearGradient>
    </Pressable>

    <View style={styles.safety}><AppIcon name="info" color={colors.ocean600} /><Text style={styles.safetyText}>Some titles include distressing topics. Read the content notes first and choose what feels safe for you today.</Text></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map(item => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item === 'ALL' ? 'All picks' : item[0] + item.slice(1).toLowerCase()}</Text></Pressable>)}</ScrollView>
    <View style={styles.sectionHead}><Text style={styles.sectionTitle}>{filter === 'ALL' ? 'Curated for thoughtful viewing' : `${filter[0] + filter.slice(1).toLowerCase()} picks`}</Text><Text style={styles.count}>{shown.length} titles</Text></View>
    <View style={styles.grid}>{shown.map(item => <MediaCard key={item.id} item={item} saved={item.saved} onSave={() => void toggleSaved(item)} />)}</View>
    <View style={styles.club}><View style={styles.clubIcon}><AppIcon name="groups" color={colors.ocean700} /></View><View style={{ flex: 1 }}><Text style={styles.clubLabel}>COMING THIS WEEK</Text><Text style={styles.clubTitle}>GreenOcean Watch Circle</Text><Text style={styles.clubText}>A moderated group discussion about anxiety and identity in Inside Out 2.</Text></View><Pressable onPress={() => router.push('/channels')} style={styles.clubButton}><Text style={styles.clubButtonText}>View group</Text></Pressable></View>
  </View></Screen>;
}

function MediaCard({ item, saved, onSave }: { item: MediaPick; saved: boolean; onSave: () => void }) {
  return <View style={styles.card}><View style={[styles.poster, { backgroundColor: item.accent }]}><View style={styles.posterCircle} /><Text style={styles.posterKind}>{item.kind}</Text><AppIcon name={item.kind === 'SERIES' ? 'live_tv' : item.kind === 'DOCUMENTARY' ? 'document_scanner' : 'movie'} size={42} color="#ffffffBB" /><Text style={styles.posterTitle}>{item.title}</Text></View><View style={styles.cardBody}><View style={styles.cardTop}><View style={{ flex: 1 }}><Text style={styles.cardTheme}>{item.theme}</Text><Text style={styles.cardMeta}>{item.year} · {item.duration}</Text></View><Pressable onPress={onSave} style={styles.save}><AppIcon name="bookmark" filled={saved} color={saved ? colors.ocean700 : colors.muted} /></Pressable></View><Text style={styles.cardDescription}>{item.description}</Text><Text style={styles.promptLabel}>DISCUSSION PROMPT</Text><Text style={styles.prompt}>{item.discussionPrompt}</Text><View style={styles.notes}>{item.contentNotes.map(note => <Text key={note} style={[styles.note, { backgroundColor: item.softAccent, color: item.accent }]}>{note}</Text>)}</View><View style={styles.by}><AppIcon name="verified" filled size={15} color={colors.ocean500} /><Text style={styles.byText}>{item.recommendedBy}</Text></View></View></View>;
}

const styles = StyleSheet.create({
  screen: { padding: 0 }, content: { width: '100%', maxWidth: layout.maxWide, alignSelf: 'center', padding: spacing.md, gap: spacing.md }, top: { flexDirection: 'row', justifyContent: 'space-between' }, back: { width: 40, height: 40, borderRadius: radius.pill, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, topIcon: { width: 40, height: 40, borderRadius: radius.pill, backgroundColor: colors.lavenderSoft, alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: colors.lavender, fontSize: 10, fontWeight: '900', letterSpacing: 1.3 }, title: { color: colors.ink, fontSize: typography.h1, fontWeight: '900', marginTop: 5 }, subtitle: { color: colors.muted, fontSize: 13, lineHeight: 20, marginTop: spacing.sm, maxWidth: 680 },
  hero: { borderRadius: radius.xl, overflow: 'hidden', ...shadow.floating }, heroGradient: { minHeight: 380, padding: spacing.xl, gap: spacing.sm }, editorPick: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#00000032', borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 5 }, editorPickText: { color: colors.white, fontSize: 8, fontWeight: '900', letterSpacing: .9 }, heroArt: { position: 'absolute', right: 50, top: 45, width: 180, height: 140, borderRadius: radius.xl, backgroundColor: '#ffffff12', alignItems: 'flex-end', justifyContent: 'center', paddingRight: spacing.lg }, emotionOrb: { position: 'absolute', width: 48, height: 48, borderRadius: 24, opacity: .9 }, heroKind: { color: '#FFFFFFBB', fontSize: 9, fontWeight: '900', marginTop: 95 }, heroTitle: { color: colors.white, fontSize: 34, fontWeight: '900' }, heroTheme: { color: colors.sun, fontSize: 12, fontWeight: '900' }, heroDescription: { color: '#FFFFFFDD', fontSize: 13, lineHeight: 20, maxWidth: 620 }, heroFooter: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.sm, marginTop: spacing.sm }, recommended: { flex: 1, minWidth: 220, flexDirection: 'row', alignItems: 'center', gap: 5 }, recommendedText: { color: colors.ocean100, fontSize: 10, fontWeight: '800' }, exploreButton: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: colors.white, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, exploreText: { color: colors.ocean950, fontSize: 10, fontWeight: '900' },
  safety: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.ocean50, borderRadius: radius.md, padding: spacing.md }, safetyText: { flex: 1, color: colors.muted, fontSize: 10, lineHeight: 16 }, filters: { gap: spacing.sm }, filter: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 9 }, filterActive: { backgroundColor: colors.ocean900, borderColor: colors.ocean900 }, filterText: { color: colors.muted, fontSize: 11, fontWeight: '800' }, filterTextActive: { color: colors.white }, sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sectionTitle: { color: colors.ink, fontSize: typography.h3, fontWeight: '900' }, count: { color: colors.muted, fontSize: 10 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, card: { flexGrow: 1, flexBasis: 310, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.xl, overflow: 'hidden', ...shadow.soft }, poster: { height: 200, padding: spacing.lg, justifyContent: 'space-between', overflow: 'hidden' }, posterCircle: { position: 'absolute', width: 250, height: 250, borderRadius: 125, backgroundColor: '#ffffff18', right: -80, top: -80 }, posterKind: { alignSelf: 'flex-start', color: colors.white, fontSize: 8, fontWeight: '900', letterSpacing: 1, backgroundColor: '#00000022', borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 4 }, posterTitle: { color: colors.white, fontSize: 24, lineHeight: 30, fontWeight: '900', maxWidth: 250 }, cardBody: { padding: spacing.md, gap: spacing.sm }, cardTop: { flexDirection: 'row', alignItems: 'center' }, cardTheme: { color: colors.ink, fontSize: 13, fontWeight: '900' }, cardMeta: { color: colors.muted, fontSize: 9, marginTop: 3 }, save: { width: 36, height: 36, borderRadius: radius.pill, backgroundColor: colors.foam, alignItems: 'center', justifyContent: 'center' }, cardDescription: { color: colors.inkSoft, fontSize: 11, lineHeight: 18 }, promptLabel: { color: colors.ocean600, fontSize: 8, fontWeight: '900', letterSpacing: .8 }, prompt: { color: colors.ink, fontSize: 11, lineHeight: 18, fontStyle: 'italic' }, notes: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 }, note: { borderRadius: radius.pill, paddingHorizontal: 7, paddingVertical: 4, fontSize: 8, fontWeight: '800' }, by: { flexDirection: 'row', alignItems: 'center', gap: 4, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.sm }, byText: { color: colors.muted, fontSize: 9, fontWeight: '800' },
  club: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.md, backgroundColor: colors.ocean950, borderRadius: radius.xl, padding: spacing.lg }, clubIcon: { width: 48, height: 48, borderRadius: radius.md, backgroundColor: colors.ocean200, alignItems: 'center', justifyContent: 'center' }, clubLabel: { color: colors.ocean300, fontSize: 8, fontWeight: '900', letterSpacing: 1 }, clubTitle: { color: colors.white, fontSize: 16, fontWeight: '900', marginTop: 3 }, clubText: { color: colors.ocean200, fontSize: 10, marginTop: 3 }, clubButton: { backgroundColor: colors.white, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, clubButtonText: { color: colors.ocean950, fontSize: 10, fontWeight: '900' },
});
