import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppIcon } from '@/components/app-icon';
import { Avatar } from '@/components/avatar';
import { Screen } from '@/components/screen';
import { usePlatformData } from '@/features/platform/data-provider';
import { Professional } from '@/features/platform/types';
import { colors, layout, radius, shadow, spacing, typography } from '@/theme/tokens';

const specialtyFilters = ['All', 'Anxiety', 'Sleep', 'Relationships', 'ADHD', 'Trauma'];

export default function ProfessionalDirectory() {
  const { professionals } = usePlatformData();
  const [query, setQuery] = useState(''); const [specialty, setSpecialty] = useState('All'); const [availableOnly, setAvailableOnly] = useState(false);
  const shown = useMemo(() => professionals.filter(pro => {
    const search = query.trim().toLowerCase();
    const matchesQuery = !search || [pro.displayName, pro.title, pro.city, pro.country, ...pro.languages, ...pro.specialties].some(item => item.toLowerCase().includes(search));
    const matchesSpecialty = specialty === 'All' || pro.specialties.some(item => item.toLowerCase().includes(specialty.toLowerCase()));
    return matchesQuery && matchesSpecialty && (!availableOnly || pro.acceptingNewClients);
  }), [query, specialty, availableOnly]);
  return <Screen scroll style={styles.screen}><View style={styles.content}>
    <View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><AppIcon name="arrow_back" color={colors.ocean700} /></Pressable><View style={styles.verified}><AppIcon name="verified_user" size={16} color={colors.ocean600} /><Text style={styles.verifiedText}>Credentials checked</Text></View></View>
    <View><Text style={styles.eyebrow}>FIND THE RIGHT FIT</Text><Text style={styles.title}>Verified professionals</Text><Text style={styles.subtitle}>Compare expertise, language, location, consultation format, and availability before starting a conversation.</Text></View>
    <View style={styles.search}><AppIcon name="search" color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Name, specialty, language, or location" placeholderTextColor={colors.muted} style={styles.input} /></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{specialtyFilters.map(item => <Pressable key={item} onPress={() => setSpecialty(item)} style={[styles.filter, specialty === item && styles.filterActive]}><Text style={[styles.filterText, specialty === item && styles.filterTextActive]}>{item}</Text></Pressable>)}</ScrollView>
    <Pressable onPress={() => setAvailableOnly(value => !value)} style={[styles.availableFilter, availableOnly && styles.availableFilterActive]}><AppIcon name={availableOnly ? 'check_box' : 'check_box_outline_blank'} filled={availableOnly} color={availableOnly ? colors.ocean700 : colors.muted} /><Text style={[styles.availableText, availableOnly && { color: colors.ocean700 }]}>Accepting new clients only</Text></Pressable>
    <View style={styles.resultHead}><Text style={styles.resultTitle}>{shown.length} professionals</Text><View style={styles.sort}><AppIcon name="sort" size={16} color={colors.muted} /><Text style={styles.sortText}>Best match</Text></View></View>
    {shown.map(pro => <ProfessionalCard key={pro.id} professional={pro} />)}
    {!shown.length && <View style={styles.empty}><AppIcon name="search_off" size={34} color={colors.ocean500} /><Text style={styles.emptyTitle}>No exact matches</Text><Text style={styles.emptyText}>Try removing a filter or searching a broader specialty.</Text></View>}
    <Text style={styles.disclaimer}>GreenOcean verifies submitted credentials but does not guarantee suitability or treatment outcomes. Confirm local licensing and care details before booking.</Text>
  </View></Screen>;
}

function ProfessionalCard({ professional }: { professional: Professional }) {
  return <Pressable onPress={() => router.push({ pathname: '/profile', params: { professional: professional.id } })} style={styles.card}>
    {professional.promoted && <View style={styles.sponsored}><AppIcon name="campaign" size={13} color={colors.muted} /><Text style={styles.sponsoredText}>SPONSORED PLACEMENT</Text></View>}
    <View style={styles.cardTop}><Avatar name={professional.displayName} size={66} verified /><View style={{ flex: 1 }}><Text style={styles.name}>{professional.displayName}</Text><Text style={styles.role}>{professional.title}</Text><Text style={styles.location}>{professional.city} · {professional.country}</Text></View><View style={styles.score}><Text style={styles.scoreValue}>{professional.greenOceanScore}</Text><Text style={styles.scoreLabel}>GO SCORE</Text></View></View>
    <Text style={styles.bio} numberOfLines={2}>{professional.bio}</Text><View style={styles.tags}>{professional.specialties.map(item => <Text key={item} style={styles.tag}>{item}</Text>)}</View>
    <View style={styles.details}><Detail icon="language" text={professional.languages.join(' · ')} /><Detail icon="person" text={professional.gender} /><Detail icon="videocam" text={professional.consultationModes.join(' · ')} /></View>
    <View style={styles.cardBottom}><View><View style={styles.rating}><AppIcon name="star" filled size={16} color={colors.sun} /><Text style={styles.ratingText}>{professional.rating} · {professional.reviewCount} reviews</Text></View><Text style={[styles.availability, !professional.acceptingNewClients && { color: colors.sun }]}>{professional.acceptingNewClients ? '● Accepting new clients' : '● Waitlist active'}</Text></View><View style={styles.profileButton}><Text style={styles.profileButtonText}>View profile</Text><AppIcon name="arrow_forward" size={17} color={colors.white} /></View></View>
  </Pressable>;
}
function Detail({ icon, text }: { icon: string; text: string }) { return <View style={styles.detail}><AppIcon name={icon} size={15} color={colors.muted} /><Text style={styles.detailText}>{text}</Text></View>; }
const styles = StyleSheet.create({
  screen: { padding: 0 }, content: { width: '100%', maxWidth: layout.maxContent, alignSelf: 'center', padding: spacing.md, gap: spacing.md }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, back: { width: 40, height: 40, borderRadius: radius.pill, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, verified: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: colors.ocean50, borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 6 }, verifiedText: { color: colors.ocean600, fontSize: 9, fontWeight: '900' },
  eyebrow: { color: colors.ocean600, fontSize: 9, fontWeight: '900', letterSpacing: 1.3 }, title: { color: colors.ink, fontSize: typography.h1, fontWeight: '900', marginTop: 4 }, subtitle: { color: colors.muted, fontSize: 12, lineHeight: 19, marginTop: spacing.sm }, search: { height: 52, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md }, input: { flex: 1, color: colors.ink, fontSize: 13, textAlign: 'left' }, filters: { gap: spacing.sm }, filter: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 9 }, filterActive: { backgroundColor: colors.ocean900, borderColor: colors.ocean900 }, filterText: { color: colors.muted, fontSize: 10, fontWeight: '800' }, filterTextActive: { color: colors.white }, availableFilter: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 8 }, availableFilterActive: { borderColor: colors.ocean300, backgroundColor: colors.ocean50 }, availableText: { color: colors.muted, fontSize: 10, fontWeight: '800' }, resultHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, resultTitle: { color: colors.ink, fontSize: typography.h3, fontWeight: '900' }, sort: { flexDirection: 'row', alignItems: 'center', gap: 4 }, sortText: { color: colors.muted, fontSize: 9 },
  card: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.xl, padding: spacing.lg, gap: spacing.sm, ...shadow.soft }, sponsored: { flexDirection: 'row', alignItems: 'center', gap: 4 }, sponsoredText: { color: colors.muted, fontSize: 7, fontWeight: '900', letterSpacing: .8 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, name: { color: colors.ink, fontSize: 17, fontWeight: '900' }, role: { color: colors.ocean600, fontSize: 11, fontWeight: '800', marginTop: 2 }, location: { color: colors.muted, fontSize: 9, marginTop: 3 }, score: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.ocean50, borderWidth: 3, borderColor: colors.ocean200, alignItems: 'center', justifyContent: 'center' }, scoreValue: { color: colors.ocean800, fontSize: 19, fontWeight: '900' }, scoreLabel: { color: colors.muted, fontSize: 6, fontWeight: '900' }, bio: { color: colors.inkSoft, fontSize: 11, lineHeight: 17 }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 }, tag: { color: colors.ocean700, backgroundColor: colors.ocean50, borderRadius: radius.pill, paddingHorizontal: 7, paddingVertical: 4, fontSize: 8, fontWeight: '800' }, details: { gap: 5 }, detail: { flexDirection: 'row', alignItems: 'center', gap: 5 }, detailText: { color: colors.muted, fontSize: 9 }, cardBottom: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.sm }, rating: { flexDirection: 'row', alignItems: 'center', gap: 4 }, ratingText: { color: colors.inkSoft, fontSize: 10, fontWeight: '800' }, availability: { color: colors.ocean600, fontSize: 9, fontWeight: '800', marginTop: 4 }, profileButton: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: colors.ocean600, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 9 }, profileButtonText: { color: colors.white, fontSize: 10, fontWeight: '900' }, empty: { alignItems: 'center', gap: spacing.sm, padding: spacing.xl, backgroundColor: colors.white, borderRadius: radius.lg }, emptyTitle: { color: colors.ink, fontWeight: '900' }, emptyText: { color: colors.muted, fontSize: 11 }, disclaimer: { color: colors.muted, fontSize: 8, lineHeight: 14, textAlign: 'center', paddingHorizontal: spacing.lg },
});
