import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/app-button';
import { AppIcon } from '@/components/app-icon';
import { Screen } from '@/components/screen';
import { colors, layout, radius, spacing, typography } from '@/theme/tokens';

const topics = [['air', 'Anxiety'], ['rainy', 'Low mood'], ['favorite', 'Relationships'], ['bedtime', 'Sleep'], ['shield', 'Trauma'], ['work', 'Burnout'], ['spa', 'Grief'], ['neurology', 'ADHD']];
const supportStyles = [['forum', 'Shared experiences', 'Stories from people who understand'], ['groups', 'Support groups', 'Moderated conversations by topic'], ['hearing', 'One-to-one listener', 'Private peer support when I need it'], ['psychology', 'Professional knowledge', 'Articles and verified expert perspectives']];

export default function Onboarding() {
  const [step, setStep] = useState(1); const [selectedTopics, setSelectedTopics] = useState<string[]>([]); const [support, setSupport] = useState(''); const [privateFeed, setPrivateFeed] = useState(true);
  function toggleTopic(topic: string) { setSelectedTopics(items => items.includes(topic) ? items.filter(item => item !== topic) : [...items, topic]); }
  function next() { if (step < 3) setStep(value => value + 1); else router.replace('/(app)'); }
  return <Screen scroll style={styles.screen}><View style={styles.content}>
    <View style={styles.top}><View style={styles.logo}><AppIcon name="waves" color={colors.ocean700} /><Text style={styles.brand}>GreenOcean</Text></View><Text style={styles.stepText}>{step} of 3</Text></View>
    <View style={styles.progress}>{[1, 2, 3].map(item => <View key={item} style={[styles.progressBar, item <= step && styles.progressActive]} />)}</View>
    {step === 1 && <><View><Text style={styles.eyebrow}>PERSONALISE YOUR SPACE</Text><Text style={styles.title}>What would you like support around?</Text><Text style={styles.subtitle}>Choose as many as you want. This changes recommendations, not what you are allowed to see.</Text></View><View style={styles.topicGrid}>{topics.map(([icon, topic]) => <Pressable key={topic} onPress={() => toggleTopic(topic)} style={[styles.topic, selectedTopics.includes(topic) && styles.topicActive]}><View style={[styles.topicIcon, selectedTopics.includes(topic) && styles.topicIconActive]}><AppIcon name={icon} color={selectedTopics.includes(topic) ? colors.white : colors.ocean700} /></View><Text style={[styles.topicText, selectedTopics.includes(topic) && styles.topicTextActive]}>{topic}</Text>{selectedTopics.includes(topic) && <AppIcon name="check_circle" filled size={18} color={colors.ocean600} />}</Pressable>)}</View></>}
    {step === 2 && <><View><Text style={styles.eyebrow}>HOW YOU WANT TO CONNECT</Text><Text style={styles.title}>What kind of support feels most comfortable?</Text><Text style={styles.subtitle}>We will place this option closer to the top of your experience.</Text></View><View style={styles.supportList}>{supportStyles.map(([icon, title, text]) => <Pressable key={title} onPress={() => setSupport(title)} style={[styles.support, support === title && styles.supportActive]}><View style={[styles.supportIcon, support === title && { backgroundColor: colors.ocean600 }]}><AppIcon name={icon} color={support === title ? colors.white : colors.ocean700} /></View><View style={{ flex: 1 }}><Text style={styles.supportTitle}>{title}</Text><Text style={styles.supportText}>{text}</Text></View>{support === title && <AppIcon name="check_circle" filled color={colors.ocean600} />}</Pressable>)}</View></>}
    {step === 3 && <><View><Text style={styles.eyebrow}>PRIVACY FIRST</Text><Text style={styles.title}>You stay in control</Text><Text style={styles.subtitle}>GreenOcean makes safety controls visible from the beginning instead of hiding them in settings.</Text></View><View style={styles.privacyCard}><View style={styles.privacyIcon}><AppIcon name="shield_lock" size={34} color={colors.ocean700} /></View><Text style={styles.privacyTitle}>Start with stronger content controls</Text><Text style={styles.privacyText}>Sensitive posts will be blurred, message requests separated, and frightening topics shown with a warning first.</Text><Pressable onPress={() => setPrivateFeed(value => !value)} style={[styles.privacyToggle, privateFeed && styles.privacyToggleActive]}><AppIcon name={privateFeed ? 'toggle_on' : 'toggle_off'} filled size={34} color={privateFeed ? colors.ocean600 : colors.muted} /><Text style={styles.privacyToggleText}>{privateFeed ? 'Recommended safety controls on' : 'Standard controls'}</Text></Pressable></View><View style={styles.boundary}><AppIcon name="health_and_safety" color={colors.ocean600} /><Text style={styles.boundaryText}>GreenOcean offers peer support and educational information. It is not an emergency service or a substitute for medical care.</Text></View></>}
    <View style={styles.actions}>{step > 1 && <Pressable onPress={() => setStep(value => value - 1)} style={styles.back}><Text style={styles.backText}>Back</Text></Pressable>}<View style={{ flex: 1 }}><AppButton label={step === 3 ? 'Enter GreenOcean' : 'Continue'} onPress={next} /></View></View>
    <Pressable onPress={() => router.replace('/(app)')}><Text style={styles.skip}>Skip for now</Text></Pressable>
  </View></Screen>;
}

const styles = StyleSheet.create({
  screen: { padding: 0 }, content: { width: '100%', maxWidth: layout.maxContent, alignSelf: 'center', padding: spacing.lg, gap: spacing.lg }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, logo: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, brand: { color: colors.ocean800, fontSize: 17, fontWeight: '900' }, stepText: { color: colors.muted, fontSize: 10, fontWeight: '800' }, progress: { flexDirection: 'row', gap: spacing.sm }, progressBar: { flex: 1, height: 5, borderRadius: 3, backgroundColor: colors.border }, progressActive: { backgroundColor: colors.ocean500 }, eyebrow: { color: colors.ocean600, fontSize: 9, fontWeight: '900', letterSpacing: 1.3 }, title: { color: colors.ink, fontSize: typography.h1, lineHeight: 39, fontWeight: '900', marginTop: 5 }, subtitle: { color: colors.muted, fontSize: 12, lineHeight: 19, marginTop: spacing.sm },
  topicGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, topic: { flexGrow: 1, flexBasis: 200, minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.sm }, topicActive: { backgroundColor: colors.ocean50, borderColor: colors.ocean400 }, topicIcon: { width: 42, height: 42, borderRadius: radius.sm, backgroundColor: colors.ocean100, alignItems: 'center', justifyContent: 'center' }, topicIconActive: { backgroundColor: colors.ocean600 }, topicText: { flex: 1, color: colors.ink, fontSize: 11, fontWeight: '900' }, topicTextActive: { color: colors.ocean800 }, supportList: { gap: spacing.sm }, support: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.md }, supportActive: { backgroundColor: colors.ocean50, borderColor: colors.ocean400 }, supportIcon: { width: 46, height: 46, borderRadius: radius.md, backgroundColor: colors.ocean100, alignItems: 'center', justifyContent: 'center' }, supportTitle: { color: colors.ink, fontSize: 12, fontWeight: '900' }, supportText: { color: colors.muted, fontSize: 9, marginTop: 3 },
  privacyCard: { alignItems: 'center', gap: spacing.sm, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.xl, padding: spacing.xl }, privacyIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: colors.ocean100, alignItems: 'center', justifyContent: 'center' }, privacyTitle: { color: colors.ink, fontSize: 18, fontWeight: '900', textAlign: 'center' }, privacyText: { color: colors.muted, fontSize: 11, lineHeight: 18, textAlign: 'center' }, privacyToggle: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.foam, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 7 }, privacyToggleActive: { backgroundColor: colors.ocean50 }, privacyToggleText: { color: colors.inkSoft, fontSize: 10, fontWeight: '800' }, boundary: { flexDirection: 'row', gap: spacing.sm, backgroundColor: colors.ocean50, borderRadius: radius.lg, padding: spacing.md }, boundaryText: { flex: 1, color: colors.muted, fontSize: 9, lineHeight: 15 }, actions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: 'auto' }, back: { minHeight: 54, justifyContent: 'center', paddingHorizontal: spacing.lg }, backText: { color: colors.ocean700, fontWeight: '900' }, skip: { color: colors.muted, fontSize: 10, fontWeight: '800', textAlign: 'center', padding: spacing.sm },
});
