export const translations = { en: {
  welcomeTitle: 'You do not have to carry it alone.', welcomeSubtitle: 'A thoughtful community for real feelings, shared experiences, and verified professional support.', noJudgement: 'No judgement', realSupport: 'Human support', verifiedProfessionals: 'Verified professionals', getStarted: 'Create an account', exploreDemo: 'Explore the demo', signIn: 'Sign in', createAccount: 'Create account', email: 'Email', password: 'Password', username: 'Username', displayName: 'Display name', birthYear: 'Birth year', countryCode: 'Country', city: 'City', loginTitle: 'Welcome back', loginSubtitle: 'Your support circle is waiting.', registerTitle: 'Join GreenOcean', registerSubtitle: 'Create a safe space that feels like yours.', profile: 'Profile', logout: 'Log out', retry: 'Try again', requiredFields: 'Please complete all required fields.', genericError: 'Something went wrong. Please try again.',
  feed: 'Home', forYou: 'For you', following: 'Following', professionalAnswers: 'Expert answers', createPost: 'Share', search: 'Explore', anonymous: 'Anonymous', like: 'Support', bookmark: 'Save', comments: 'Comments', feedEmpty: 'No stories yet. Share the first one.', sharePrompt: 'Share what is on your mind…', publish: 'Publish', public: 'Public', followers: 'Followers', postAnonymously: 'Share anonymously', contentWarning: 'Content note (optional)', people: 'People', posts: 'Stories', follow: 'Follow', reply: 'Reply', send: 'Send', writeComment: 'Write a kind, supportive response…', loadMore: 'Load more',
  communities: 'Circles', notifications: 'Activity', discoverCommunities: 'Find a circle where you feel understood', createCommunity: 'Create a circle', communityName: 'Circle name', communitySlug: 'URL name', description: 'Description', privateCommunity: 'Private circle', members: 'members', join: 'Join', joined: 'Joined', leave: 'Leave', shareHere: 'Share here', noCommunities: 'No circles found.', privateInviteOnly: 'This circle is private and invitation-only.', communityPosts: 'Stories from this circle', noCommunityPosts: 'No stories have been shared here yet.', notificationEmpty: 'You are all caught up.', markAllRead: 'Mark all as read', notificationLike: 'supported your story', notificationComment: 'responded to your story', notificationReply: 'replied to your comment', notificationFollow: 'started following you', notificationCommentLike: 'supported your comment', notificationProfessional: 'left a professional response',
  featuredExperts: 'Professionals for today', promoted: 'Featured', verified: 'Verified', yearsExperience: 'years experience', reviews: 'reviews', helpful: 'Helpful', professionalResponse: 'Professional perspective', seeAll: 'See all', trendingTopics: 'Explore by category', moodQuestion: 'How are you feeling today?', editProfile: 'Edit profile', stories: 'Stories', saved: 'Saved', about: 'About', languages: 'Languages', credentials: 'Credentials verified', rating: 'Rating', demoMode: 'Preview mode', safetyNote: 'GreenOcean is a peer-support community and is not a substitute for emergency or medical care.',
  categories: 'Categories', chooseCategory: 'Choose a category', chooseCategoryHelp: 'Help others find and understand your story. Select the category that fits best.', allCategories: 'All', experience: 'Lived experience', question: 'Seeking support', reflection: 'Reflection',
} } as const;
export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;
